name: Build Regular

on:
  pull_request:
    branches:
      - a10-server
  push:
    branches:
      - F42
      - a10
      - a10s
      - a10-server
  schedule:
    - cron: "0 1 * * TUE" #Â Every Tuesday at 1am UTC
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/reusable-build-image.yml
    secrets: inherit
    with:
      image-name: ${{ github.ref_name }}
      major-version: ${{ github.ref_name == 'a10' && '10' || github.ref_name == 'a10s' && '10s' || github.ref_name == 'F42' && '42' || github.ref_name == 'main' && 'stream10' || github.ref_name }}
      default-tag: ${{ github.ref_name == 'main' && 'lts' || 'latest' }}
      rechunk: ${{ github.event_name != 'pull_request' }}
      sbom: ${{ github.event_name != 'pull_request' }}
      publish: ${{ github.event_name != 'pull_request' }}
      platforms: ${{ github.ref_name == 'albacore-server' && 'linux/arm64,linux/amd64,linux/amd64/v2' || github.ref_name == 'albacore' && 'linux/arm64,linux/amd64,linux/amd64/v2'  || github.ref_name == 'yellowfin' && 'linux/arm64,linux/amd64,linux/amd64/v2'  || 'linux/arm64,linux/amd64'  }}
