name: Build DX

on:
  pull_request:
    branches:
      - albacore
      - yellowfin
      - bluefin-tuna
      - main
  schedule:
    - cron: "0 1 * * TUE" #Â Every Tuesday at 1am UTC
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  # First build the regular image that DX will be based on
  build-regular:
    uses: ./.github/workflows/reusable-build-image.yml
    secrets: inherit
    with:
      image-name: ${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.pull_request.number) || format('{0}', github.ref_name) }}
      flavor: regular
      major-version: ${{ github.ref_name == 'albacore-server' && '10' ||github.ref_name == 'albacore' && '10' || github.ref_name == 'yellowfin' && '10s' || github.ref_name == 'bluefin-tuna' && '42' || github.ref_name == 'main' && 'stream10' || github.ref_name }}
      default-tag: ${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.pull_request.number) || (github.ref_name == 'albacore-server' && '10' || github.ref_name == 'albacore' && '10' || github.ref_name == 'yellowfin' && '10s' || github.ref_name == 'bluefin-tuna' && 'F42' || github.ref_name == 'main' && 'stream10' || github.ref_name) }}
      rechunk: ${{ github.event_name != 'pull_request' }}
      sbom: ${{ github.event_name != 'pull_request' }}
      publish: ${{ github.event_name != 'pull_request' }}
      platforms: ${{ github.ref_name == 'albacore-server' && 'linux/arm64,linux/amd64,linux/amd64/v2' || github.ref_name == 'albacore' && 'linux/arm64,linux/amd64,linux/amd64/v2'  || github.ref_name == 'yellowfin' && 'linux/arm64,linux/amd64,linux/amd64/v2'  || 'linux/arm64,linux/amd64'  }}
      image-desc: ${{ github.ref_name == 'albacore-server' && 'ğŸŸ Server variant of Albacore' || github.ref_name == 'albacore' && 'ğŸŸ Based on AlmaLinux 10.0 Almalinux' || github.ref_name == 'yellowfin' && 'ğŸ  Based on AlmaLinux Kitten 10' || github.ref_name == 'bluefin-tuna' && 'ğŸ£ Based on Fedora 42' || github.ref_name == 'main' && 'Bluefin LTS' || github.ref_name }}

  # Then build DX FROM the regular image
  build-dx:
    needs: build-regular
    uses: ./.github/workflows/reusable-build-image.yml
    secrets: inherit
    with:
      image-name: ${{ github.event_name == 'pull_request' && format('pr-{0}-dx', github.event.pull_request.number) || format('{0}-dx', github.ref_name) }}
      flavor: dx
      major-version: ${{ github.ref_name == 'albacore-server' && '10' ||github.ref_name == 'albacore' && '10' || github.ref_name == 'yellowfin' && '10s' || github.ref_name == 'bluefin-tuna' && '42' || github.ref_name == 'main' && 'stream10' || github.ref_name }}
      default-tag: ${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.pull_request.number) || (github.ref_name == 'albacore-server' && '10' || github.ref_name == 'albacore' && '10' || github.ref_name == 'yellowfin' && '10s' || github.ref_name == 'bluefin-tuna' && 'F42' || github.ref_name == 'main' && 'stream10' || github.ref_name) }}
      rechunk: ${{ github.event_name != 'pull_request' }}
      sbom: ${{ github.event_name != 'pull_request' }}
      publish: ${{ github.event_name != 'pull_request' }}
      platforms: ${{ github.ref_name == 'albacore-server' && 'linux/arm64,linux/amd64,linux/amd64/v2' || github.ref_name == 'albacore' && 'linux/arm64,linux/amd64,linux/amd64/v2'  || github.ref_name == 'yellowfin' && 'linux/arm64,linux/amd64,linux/amd64/v2'  || 'linux/arm64,linux/amd64'  }}
      image-desc: ${{ github.ref_name == 'albacore-server' && 'ğŸŸ Server variant of Albacore DX' || github.ref_name == 'albacore' && 'ğŸŸ Based on AlmaLinux 10.0 Almalinux DX' || github.ref_name == 'yellowfin' && 'ğŸ  Based on AlmaLinux Kitten 10 DX' || github.ref_name == 'bluefin-tuna' && 'ğŸ£ Based on Fedora 42 DX' || github.ref_name == 'main' && 'Bluefin LTS DX' || format('{0} DX', github.ref_name) }}
      # Chain from the regular build - use the manifest created by build-regular
      chain-base-image: ${{ format('ghcr.io/{0}/{1}:{2}', github.repository_owner, github.event_name == 'pull_request' && format('pr-{0}', github.event.pull_request.number) || github.ref_name, github.event_name == 'pull_request' && format('pr-{0}', github.event.pull_request.number) || (github.ref_name == 'albacore-server' && '10' || github.ref_name == 'albacore' && '10' || github.ref_name == 'yellowfin' && '10s' || github.ref_name == 'bluefin-tuna' && 'F42' || github.ref_name == 'main' && 'stream10' || github.ref_name)) }}
